language: python

python:
  - "3.5"
before_script:
  - sudo apt-get install -y libav-tools
  - sudo apt-get install -y libavcodec-extra-*
  - wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
  - tar xvfJ ffmpeg-git-64bit-static.tar.xz
  - sudo mv ffmpeg-git-*/ffmpeg /usr/bin/ffmpeg
  - sudo pip install playlistfromsong
install:
  # python
  - pip install -e .
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)